name: GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate GitHub stats
        uses: cicirello/user-statistician@v1
        with:
          github-username: syedmukheeth
          svg-out-file: github-stats.svg
          charts: radar
          theme: dark

      - name: Commit and push stats
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add github-stats.svg
          git commit -m "Update GitHub stats" || echo "No changes to commit"
          git push

