name: GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *' # runs every day at midnight UTC
  workflow_dispatch: # allows manual run

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate stats
        uses: cicirello/user-statistician@v1
        with:
          github-username: syedmukheeth
          svg-out-file: github-stats.svg
          theme: dark # you can try light too
          # You can tweak options for radar chart styles

      - name: Commit and push stats
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add github-stats.svg
          git commit -m "Update GitHub stats"
          git push
